version: '3'

services:
  app:
    container_name: catalog_app
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../src/:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ../.env

  db:
    container_name: catalog_db
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - ../mongodata:/data/db
    env_file:
      - ../.env
