version: '3'

services:
  app:
    container_name: catalog_app
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../src/:/app/src
      - ../docker/:/app/docker/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ../.env

  db:
    container_name: catalog_db
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - ../mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file:
      - ../.env

  mongo-express:
    image: mongo-express:1-20-alpine3.19
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_URI}
      ME_CONFIG_BASICAUTH_USERNAME: ${EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${EXPRESS_PASSWORD}
    env_file:
      - ../.env
    depends_on:
      - db

